name: riverpod_bookstore

packages:
  - packages/**

scripts:
  analyze:
    run: melos exec -c 1 -- flutter analyze .
    description: Run analyze in all packages

  generate:
    run: melos run generate:api | melos run generate:app
    description: Build all generated files

  generate:app:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Build generated files for the app package

  generate:api:
    run: melos exec -c 1 --depends-on="build_runner" --no-flutter -- "pub run build_runner build --delete-conflicting-outputs"
    description: Build generated files for the API package

  test:
    run: melos run test:flutter & melos run test:dart
    description: Run all tests

  test:flutter:
    run: melos exec --dir-exists="test" -c 1 --fail-fast -- "flutter test"
    description: Run Flutter tests for all flutter packages
    select-package:
      flutter: true
      dir-exists: test

  test:dart:
    run: melos exec --dir-exists="test" -c 1 --fail-fast -- "pub run test"
    description: Run Dart tests for all dart packages
    select-package:
      flutter: false
      dir-exists: test

  build:apk:
    run: melos exec -c 4 --fail-fast -- "flutter build apk"
    description: Build Release APK
    select-package:
      flutter: true