name: riverpod_bookstore_api
version: 0.0.1
description: API classes for a bookstore app

environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  freezed_annotation: ^0.15.0
  riverpod: ^1.0.0
dev_dependencies:
  freezed: ^0.15.0
  test: ^1.19.3
  mockito: 
  build_runner: ^2.1.4
