name: riverpod_bookstore_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^0.14.0 
  riverpod: ^1.0.0
  flutter_riverpod: ^1.0.0
  riverpod_bookstore_api:
    path: ../api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^0.14.5  
  build_runner: ^2.1.4

flutter:
  uses-material-design: true
