name: riverpod_bookstore_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^0.15.0 
  riverpod: ^1.0.0
  flutter_riverpod: ^1.0.0
  riverpod_bookstore_api:
    path: ../api
  firebase_core: ^1.10.0
  firebase_crashlytics: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10
  flutter_lints: ^1.0.0
  freezed: ^0.15.0  
  build_runner: ^2.1.4
  mockito: ^5.0.16

flutter:
  uses-material-design: true
